// <auto-generated />
using System;
using BelajaraJoinTable.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BelajaraJoinTable.Migrations
{
    [DbContext(typeof(SispelDbContext))]
    partial class SispelDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("BelajaraJoinTable.Models.Pelajaran", b =>
                {
                    b.Property<int>("IdPelajaran")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPelajaran"), 1L, 1);

                    b.Property<string>("NamaPelajaran")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdPelajaran");

                    b.ToTable("Pelajaran");
                });

            modelBuilder.Entity("BelajaraJoinTable.Models.Siswa", b =>
                {
                    b.Property<int>("IdSiswa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdSiswa"), 1L, 1);

                    b.Property<string>("Alamat")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GolonganDarah")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("Hobi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("JenisKelamin")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nama")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NomorHandphone")
                        .IsRequired()
                        .HasColumnType("nvarchar(12)");

                    b.Property<DateTime>("TanggalLahir")
                        .HasColumnType("datetime2");

                    b.Property<string>("TinggiBadan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdSiswa");

                    b.ToTable("Siswa");
                });

            modelBuilder.Entity("BelajaraJoinTable.Models.SiswaPelajaran", b =>
                {
                    b.Property<int>("IdSiswaPelajaran")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdSiswaPelajaran"), 1L, 1);

                    b.Property<int>("IdPelajaran")
                        .HasColumnType("int");

                    b.Property<int>("IdSiswa")
                        .HasColumnType("int");

                    b.HasKey("IdSiswaPelajaran");

                    b.HasIndex("IdPelajaran");

                    b.HasIndex("IdSiswa");

                    b.ToTable("SiswaPelajaran");
                });

            modelBuilder.Entity("BelajaraJoinTable.Models.SiswaPelajaran", b =>
                {
                    b.HasOne("BelajaraJoinTable.Models.Pelajaran", "Pelajaran")
                        .WithMany()
                        .HasForeignKey("IdPelajaran")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BelajaraJoinTable.Models.Siswa", "Siswa")
                        .WithMany()
                        .HasForeignKey("IdSiswa")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pelajaran");

                    b.Navigation("Siswa");
                });
#pragma warning restore 612, 618
        }
    }
}
